[package]
name = "cheval"
version = "0.1.0"
authors = ["Andreas Neukoetter <andreas@omni-mad.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="cheval"
path="src/cheval_main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
image = "0.23.8"

[target.'cfg(target_arch = "x86_64")'.dependencies]
minifb = "0.18.0"

[target.'cfg(target_arch = "arm")'.dependencies]
framebuffer = "0.2.0"
