name:  Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11]
#        os: [ubuntu-latest, macos-11, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
#          target: aarch64-apple-darwin
          target: x86_64-apple-darwin

      - name: Cache crates
        uses: actions/cache@v2
        env:
          cache-name: cache-crates
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-x86_64-apple-darwin-${{ hashFiles('Cargo.lock') }}

      - name: Run cargo build --release for Intel
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release --target x86_64-apple-darwin


      - name: Run cargo test --release for Intel
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --target x86_64-apple-darwin

