name: publish_crates

on:
  push:
    tags:
      - "*-beta"
      - "*-alpha"
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: katyo/publish-crates@v1
        with:
          path: '.'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
#          args: --no-verify
#          dry-run: true
